### ISSUE TITLE
Scanning frequency low when using this driver (~1hz)

### ISSUE THREAD

**Issue by ridhwankamil** [AutonicsLiDAR/lsc_ros_driver#1]
Im having issue when using this package, scanning frequency is around ~1hz,
no issue when using atLidar software

**Comment by ridhwankamil** [comment]
i also observe quiet high cpu usage

**Comment by Autonics-lidar** [comment]
Hi, 

I found that the cpu overhead is occured in https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L325

To solve this problem, 
declear "ros::Rate loop_rate(200);" in https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L311
and insert "loop_rate.sleep();" under https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L343
I will reflect this issue in next update~!


And for the scanning frequency issue above,  check frequency with diagnostic updater (rostopic echo /diagnositcs)
If you leave more details about this issue, it will be helpful to check it out

thanks!

**Comment by Autonics-lidar** [comment]
Hi, 

I found that the cpu overhead is occured in https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L325

To solve this problem, 
declear "ros::Rate loop_rate(200);" in https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L311
and insert "loop_rate.sleep();" under https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L343
I will reflect this issue in next update~!


And for the scanning frequency issue above,  check frequency with diagnostic updater (rostopic echo /diagnositcs)
If you leave more details about this issue, it will be helpful to check it out

thanks!

**Comment by Autonics-lidar** [comment]
Hi, 

I found that the cpu overhead is occured in https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L325

To solve this problem, 
declear "ros::Rate loop_rate(200);" in https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L311
and insert "loop_rate.sleep();" under https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L343
I will reflect this issue in next update~!


And for the scanning frequency issue above,  check frequency with diagnostic updater (rostopic echo /diagnositcs)
If you leave more details about this issue, it will be helpful to check it out

thanks!

**Comment by ridhwankamil** [comment]
Hi, @Autonics-lidar by adding the sleep does reduce the cpu usage.

here is the screenshot of diagnostic
![diagnostic](https://user-images.githubusercontent.com/77251176/193182863-395d0b80-51d7-4c96-9136-00ed6fd0b542.png)
![hz_scan](https://user-images.githubusercontent.com/77251176/193182870-947ab086-e2d5-4976-a844-896bd38aa87b.png)

**Comment by Autonics-lidar** [comment]
@ridhwankamil 
Unfortunately I couldn't reproduce the behavior you mentioned.
I checked operation time from receiving datas to publishing topic message, it takes less than 1ms.

In this video, topic message is published with regular period, It seems like device sends data with specific period.
https://drive.google.com/file/d/1YquLyV9lDUvIIqcg6dBNhaLBG2VZ2q9N/view

So, I suggest you to try these steps below
 1. Initialize LSC device via atLiDAR(press initialization button)
 2. Check if "Scan Data Cycle" is set as '1'
 3. Run lsc_ros_driver again

![atlidar_initialization](https://user-images.githubusercontent.com/107964762/193754281-802c51e8-b1c8-41ec-ae27-5abf3163f03d.jpg)

Best regards

**Comment by ridhwankamil** [comment]
HI @Autonics-lidar, i just managed to test on different PC,

**1st test - (illegear ionic)**
Network adapter -Realtek RTL8168
Driver - default from kernel
Issue -Slow scanning frequency

**2nd test on (intel nuc NUCH11PAHi7)**
Network adapter - Intel® Ethernet Controller i225-V
Driver - Default from kernel
Issue - Network adapters sometimes did not detect the LAN plug-in & sometimes the connection drop


I managed to solve above issue  on both pc using cheap usb to ethernet adapter, i think this is driver related issue

**Comment by Autonics-lidar** [comment]
Thanks for your feedback
We will refer to this for improvement

thank you!

**Comment by ridhwankamil** [comment]
Since i manage to solve this by using external usb to ethernet adapter, i will close this issue

**Comment by autonicsjb** [comment]
> Hi,
> 
> I found that the cpu overhead is occured in
> 
> https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L325
> 
> To solve this problem, declear "ros::Rate loop_rate(200);" in
> 
> https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L311
> 
> 
> and insert "loop_rate.sleep();" under
> https://github.com/AutonicsLiDAR/lsc_ros_driver/blob/f7bb67acd1767593f3e22cbed92713a6edfa4f51/src/laser.cpp#L343
> 
> 
> I will reflect this issue in next update~!
> And for the scanning frequency issue above, check frequency with diagnostic updater (rostopic echo /diagnositcs) If you leave more details about this issue, it will be helpful to check it
> 
> thanks!

HI ~ I'm Mal Autonics's (JB) office sales engineer - J.Y. Leong, may I follow up the updated version on ROS Drive, is it avaible for download at Autonics's Website ?
