### ISSUE TITLE
Follow up the new update for ROS driver 

### ISSUE THREAD

**Issue by autonicsjb** [AutonicsLiDAR/lsc_ros_driver#2]
Good Day ~ May I follow up the update for the ROS driver as below massage ? We would like to start the AGV project soon, hope can receive your reply soon. Thank You. 

![image](https://user-images.githubusercontent.com/119997963/206333249-ab95f699-0e3a-4384-afe4-2cc5e25497db.png)

**Comment by Autonics-lidar** [comment]
Hi, I'm sorry for late reply.
Unfortunately, I think it will take about 2weeks because of extra test and internal process.

Additionally, If you use CMS, you can get faster response.
Thank you.
